language: node_js
node_js:
  - "6.2.0"
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - sudo apt-get install google-chrome-stable
  
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install